import os
import whisper
from jiwer import wer, cer, Compose, RemovePunctuation, ToLowerCase, RemoveMultipleSpaces, Strip

transform = Compose([
    ToLowerCase(),
    RemovePunctuation(),
    RemoveMultipleSpaces(),
    Strip()
])

model = whisper.load_model("base")

audio_path = "data/processed/clean_30s.wav"
hypothesis_path = "data/hypothesis.txt"
reference_path = "data/reference.txt"

# Load or produce hypothesis: prefer existing hypothesis file if non-empty
hypothesis = None
if os.path.exists(hypothesis_path) and os.path.getsize(hypothesis_path) > 0:
    with open(hypothesis_path, "r", encoding="utf-8") as f:
        hypothesis = f.read()
else:
    print("No hypothesis file found or it's empty — transcribing audio to produce hypothesis...")
    result = model.transcribe(audio_path, language="en", fp16=False)
    hypothesis = result.get("text", "")
    # Save hypothesis for reproducibility
    os.makedirs(os.path.dirname(hypothesis_path), exist_ok=True)
    with open(hypothesis_path, "w", encoding="utf-8") as f:
        f.write(hypothesis)

# Load reference (expected ground truth)
if not os.path.exists(reference_path):
    raise FileNotFoundError(f"Reference file not found: {reference_path}")
with open(reference_path, "r", encoding="utf-8") as f:
    reference = f.read()

# Normalize texts before scoring
reference = transform(reference)
hypothesis = transform(hypothesis)

# If reference equals hypothesis after normalization, warn the user
if reference == hypothesis:
    print("\nWARNING: reference and hypothesis are identical after normalization.")
    print("This usually means `data/reference.txt` was generated by the model or copied from the hypothesis.")
    print("WER/CER of 0% is not meaningful unless `data/reference.txt` is a human-generated ground truth.")

wer_score = wer(reference, hypothesis)
cer_score = cer(reference, hypothesis)

print("\nEvaluation Results")
print("----------------------------")
print(f"WER: {wer_score * 100:.2f}%")
print(f"CER: {cer_score * 100:.2f}%")

os.makedirs("results", exist_ok=True)
with open("results/wer_report.txt", "w", encoding="utf-8") as f:
    f.write(f"WER: {wer_score * 100:.2f}%\n")
    f.write(f"CER: {cer_score * 100:.2f}%\n")