"""Module for exporting meeting summaries and sending emails."""

import smtplib
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formatdate
from pathlib import Path
from typing import Optional


class ExportManager:
    """Manages exporting meeting summaries and sending emails."""

    @staticmethod
    def build_markdown_report(
        title: str,
        summary: str,
        diarized_transcript: str,
        transcript_text: str,
        created_at: str,
    ) -> str:
        """
        Build a markdown report from meeting data.

        Args:
            title: Meeting title
            summary: Meeting summary
            diarized_transcript: Transcript with speaker identification
            transcript_text: Raw transcript text
            created_at: Creation timestamp

        Returns:
            Formatted markdown report as string
        """
        report = f"""# Meeting Summary Report

**Title:** {title}  
**Created:** {created_at}

---

## Executive Summary

{summary}

---

## Full Transcript (Diarized)

{diarized_transcript}

---

## Raw Transcript

{transcript_text}

---

*Report generated by Live Meeting Summarizer Application*
"""
        return report

    @staticmethod
    def send_email(
        subject: str,
        body: str,
        to_email: str,
        from_email: str,
        password: str,
        smtp_server: str = "smtp.gmail.com",
        smtp_port: int = 587,
        attachments: Optional[list[str]] = None,
    ) -> tuple[bool, str]:
        """
        Send email with optional attachments.

        Args:
            subject: Email subject
            body: Email body content
            to_email: Recipient email address
            from_email: Sender email address
            password: Email account password or app password
            smtp_server: SMTP server address
            smtp_port: SMTP server port
            attachments: List of file paths to attach

        Returns:
            Tuple of (success: bool, message: str)
        """
        try:
            # Create message
            msg = MIMEMultipart()
            msg["From"] = from_email
            msg["To"] = to_email
            msg["Subject"] = subject
            msg["Date"] = formatdate(localtime=True)

            # Attach body
            msg.attach(MIMEText(body, "markdown"))

            # Attach files if provided
            if attachments:
                for file_path in attachments:
                    try:
                        attach_file = Path(file_path)
                        if attach_file.exists():
                            with open(attach_file, "rb") as attachment:
                                part = MIMEBase("application", "octet-stream")
                                part.set_payload(attachment.read())
                                part.add_header(
                                    "Content-Disposition",
                                    f"attachment; filename= {attach_file.name}",
                                )
                                msg.attach(part)
                    except Exception as e:
                        return False, f"Error attaching {file_path}: {str(e)}"

            # Send email
            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(from_email, password)
                server.send_message(msg)

            return True, "Email sent successfully!"

        except smtplib.SMTPAuthenticationError:
            return False, "Authentication failed. Check email and password."
        except smtplib.SMTPException as e:
            return False, f"SMTP error: {str(e)}"
        except Exception as e:
            return False, f"Error sending email: {str(e)}"
