"""Session logger for storing meeting recordings and transcripts."""

import json
from datetime import datetime
from pathlib import Path
from typing import Optional

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
    from reportlab.lib.enums import TA_LEFT, TA_CENTER
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


class SessionLogger:
    """Handles logging and storing meeting session data."""

    def __init__(self, base_dir: str = "results/sessions") -> None:
        """
        Initialize the session logger.

        Args:
            base_dir: Base directory for storing session data
        """
        self.base_dir = Path(base_dir)
        self.base_dir.mkdir(parents=True, exist_ok=True)

    def save_session(
        self,
        title: str,
        meeting_type: str,
        audio_path: Optional[str],
        transcript_segments: list,
        diarized_segments: list,
        transcript_text: str,
        diarized_transcript: str,
        summary: str,
        status_messages: list,
    ) -> dict:
        """
        Save a complete meeting session to disk.

        Args:
            title: Meeting title
            meeting_type: Type of meeting
            audio_path: Path to audio file
            transcript_segments: Original transcript segments
            diarized_segments: Diarized transcript segments
            transcript_text: Plain text transcript
            diarized_transcript: Formatted diarized transcript
            summary: Meeting summary
            status_messages: Status messages from processing

        Returns:
            Dictionary with paths to saved files
        """
        try:
            # Create session directory with timestamp
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            session_dir = self.base_dir / f"{timestamp}_{title.replace(' ', '-').lower()}"
            session_dir.mkdir(parents=True, exist_ok=True)

            # Save session metadata as JSON
            session_json_path = session_dir / "session.json"
            session_data = {
                "title": title,
                "meeting_type": meeting_type,
                "created_at": datetime.now().isoformat(),
                "status_messages": status_messages,
                "audio_path": str(audio_path) if audio_path else None,
            }
            with open(session_json_path, "w", encoding="utf-8") as f:
                json.dump(session_data, f, indent=2)

            # Save markdown summary
            markdown_path = session_dir / "meeting_summary.md"
            markdown_content = f"""# {title}

**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Type:** {meeting_type}

## Summary

{summary}

## Diarized Transcript

{diarized_transcript}

## Full Transcript

{transcript_text}

---
*Generated by Live Meeting Summarizer Application*
"""
            with open(markdown_path, "w", encoding="utf-8") as f:
                f.write(markdown_content)

            # Save transcript JSON for programmatic access
            transcript_json_path = session_dir / "transcript.json"
            transcript_data = {
                "title": title,
                "meeting_type": meeting_type,
                "created_at": datetime.now().isoformat(),
                "summary": summary,
                "segments": transcript_segments,
                "diarized_segments": diarized_segments,
            }
            with open(transcript_json_path, "w", encoding="utf-8") as f:
                json.dump(transcript_data, f, indent=2)

            # Save plain text transcript
            transcript_txt_path = session_dir / "transcript.txt"
            with open(transcript_txt_path, "w", encoding="utf-8") as f:
                f.write(f"{title}\n")
                f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"Type: {meeting_type}\n")
                f.write("=" * 50 + "\n\n")
                f.write(diarized_transcript if diarized_transcript else transcript_text)

            # Generate PDF
            pdf_path = session_dir / f"{title.replace(' ', '_')}_summary.pdf"
            self._generate_pdf(
                pdf_path=str(pdf_path),
                title=title,
                meeting_type=meeting_type,
                summary=summary,
                diarized_transcript=diarized_transcript,
                transcript_text=transcript_text,
            )

            return {
                "session_dir": str(session_dir),
                "session_json_path": str(session_json_path),
                "markdown_path": str(markdown_path),
                "transcript_json_path": str(transcript_json_path),
                "transcript_txt_path": str(transcript_txt_path),
                "pdf_path": str(pdf_path),
                "audio_path": str(audio_path) if audio_path else None,
                "timestamp": timestamp,
            }

        except Exception as e:
            raise RuntimeError(f"Error saving session: {str(e)}")

    def _generate_pdf(
        self,
        pdf_path: str,
        title: str,
        meeting_type: str,
        summary: str,
        diarized_transcript: str,
        transcript_text: str,
    ) -> None:
        """
        Generate a PDF report from meeting data.

        Args:
            pdf_path: Path where PDF should be saved
            title: Meeting title
            meeting_type: Type of meeting
            summary: Meeting summary
            diarized_transcript: Formatted diarized transcript
            transcript_text: Plain text transcript
        """
        if not HAS_REPORTLAB:
            # If reportlab is not available, create a simple text-based PDF-like file
            with open(pdf_path, "w", encoding="utf-8") as f:
                f.write(f"Meeting Summary Report\n")
                f.write(f"{'=' * 80}\n\n")
                f.write(f"Title: {title}\n")
                f.write(f"Type: {meeting_type}\n")
                f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
                f.write(f"SUMMARY\n{'-' * 80}\n{summary}\n\n")
                f.write(f"DIARIZED TRANSCRIPT\n{'-' * 80}\n{diarized_transcript}\n\n")
                f.write(f"FULL TRANSCRIPT\n{'-' * 80}\n{transcript_text}\n")
            return

        try:
            doc = SimpleDocTemplate(pdf_path, pagesize=letter)
            styles = getSampleStyleSheet()
            story = []

            # Title
            title_style = ParagraphStyle(
                "CustomTitle",
                parent=styles["Heading1"],
                fontSize=24,
                textColor="#1f2933",
                spaceAfter=12,
                alignment=TA_CENTER,
            )
            story.append(Paragraph(title, title_style))

            # Meeting info
            info_style = ParagraphStyle(
                "Info",
                parent=styles["Normal"],
                fontSize=10,
                textColor="#52606d",
                spaceAfter=6,
            )
            story.append(Paragraph(f"<b>Type:</b> {meeting_type}", info_style))
            story.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", info_style))
            story.append(Spacer(1, 0.3 * inch))

            # Summary section
            heading_style = ParagraphStyle(
                "CustomHeading",
                parent=styles["Heading2"],
                fontSize=14,
                textColor="#1f2933",
                spaceAfter=8,
                spaceBefore=8,
            )
            story.append(Paragraph("Executive Summary", heading_style))

            body_style = ParagraphStyle(
                "CustomBody",
                parent=styles["Normal"],
                fontSize=10,
                spaceAfter=6,
            )
            story.append(Paragraph(summary, body_style))
            story.append(Spacer(1, 0.2 * inch))

            # Transcript sections
            story.append(Paragraph("Diarized Transcript", heading_style))
            for line in diarized_transcript[:2000].split("\n"):
                if line.strip():
                    story.append(Paragraph(line, body_style))

            story.append(PageBreak())
            story.append(Paragraph("Full Transcript", heading_style))
            for line in transcript_text[:2000].split("\n"):
                if line.strip():
                    story.append(Paragraph(line, body_style))

            doc.build(story)

        except Exception as e:
            # Fallback: save as text if PDF generation fails
            with open(pdf_path, "w", encoding="utf-8") as f:
                f.write(f"Meeting Summary Report\n")
                f.write(f"{'=' * 80}\n\n")
                f.write(f"Title: {title}\n")
                f.write(f"Type: {meeting_type}\n")
                f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
                f.write(f"SUMMARY\n{'-' * 80}\n{summary}\n")

    def get_session_summary(self, session_dir: str) -> Optional[dict]:
        """
        Load a previously saved session.

        Args:
            session_dir: Path to the session directory

        Returns:
            Session data dictionary or None if not found
        """
        try:
            session_path = Path(session_dir)
            session_json = session_path / "session.json"

            if not session_json.exists():
                return None

            with open(session_json, "r", encoding="utf-8") as f:
                return json.load(f)

        except Exception as e:
            print(f"Error loading session: {str(e)}")
            return None

    def list_sessions(self) -> list:
        """
        List all saved sessions.

        Returns:
            List of session directory paths
        """
        try:
            return sorted([str(d) for d in self.base_dir.iterdir() if d.is_dir()], reverse=True)
        except Exception as e:
            print(f"Error listing sessions: {str(e)}")
            return []
